### ISSUE TITLE
Required upgrade from obsolete version of php ^7.4

### ISSUE THREAD

**Issue by margori** [robiasto/codeception-maildev-module#2]
Currently this module requires php 7.4 to work which [has reached end of life ](https://www.php.net/eol.php).

Upgrade to php 8 is needed.

**Comment by Mabahe** [comment]
I stopped pushing commits to this repo and forked my own package.
Please check my fork for newer versions https://github.com/Mabahe/codeception-maildev-module

**Comment by margori** [comment]
Nice! Using the new package. Thanks a lot!
